"""The table behind a browser's session cookie.

A new table rather than columns on ``api_key``, which is the shape this repository
usually prefers and is wrong here. The two credentials differ in the one column
that matters -- a key is valid until revoked, a session until it expires -- so one
table would mean a nullable ``expires_at`` plus a rule, enforceable nowhere, that
key rows must not have one and session rows must. See
`docs/adr/0005-a-browser-holds-a-session-not-a-key.md`.

Safe to apply to a database with rows in it, which is the check this repository
keeps a note about: everything here is ``CREATE TABLE``, so there is no
``ADD COLUMN ... NOT NULL`` without a default to fail against real data while
passing on an empty development one. Applied to a database holding thirty-one
api_key rows before being committed.

No foreign key from ``principal_id`` to anything, matching ``api_key`` and
``chat_session.user_id``: there is no accounts table, deliberately, and
`docs/adr/0004-authentication-is-shared-authorization-lives-next-to-the-resource.md`
records why inventing one here would be the wrong fix.

Revision ID: 0057489a3ed5
Revises: 09a68f10e5a5
Create Date: 2026-08-19 18:33:40.303924
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0057489a3ed5"
down_revision: Union[str, None] = "09a68f10e5a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "browser_session",
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("principal_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_browser_session_principal_id"), "browser_session", ["principal_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_browser_session_principal_id"), table_name="browser_session")
    op.drop_table("browser_session")
    # ### end Alembic commands ###
