"""initial schema

Revision ID: 5dfc3e977522
Revises:
Create Date: 2026-08-06 22:58:32.130515
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "5dfc3e977522"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key",
        sa.Column("key_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("principal_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key_id"),
    )
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_key_principal_id"), ["principal_id"], unique=False)

    op.create_table(
        "chat_session",
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("working_state", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("chat_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_session_user_id"), ["user_id"], unique=False)

    op.create_table(
        "ingestion_batch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_count", sa.Integer(), nullable=False),
        sa.Column("rejected_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingestion_batch", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingestion_batch_source"), ["source"], unique=False)

    op.create_table(
        "chat_memory_entry",
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_session.session_id"],
        ),
        sa.PrimaryKeyConstraint("session_id", "key"),
    )
    op.create_table(
        "chat_transcript_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_session.session_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_transcript_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_chat_transcript_item_seq"), ["seq"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_chat_transcript_item_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "ingested_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["ingestion_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ingested_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ingested_record_batch_id"), ["batch_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ingested_record_external_id"), ["external_id"], unique=False
        )

    op.create_table(
        "rejected_record",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["ingestion_batch.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rejected_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rejected_record_batch_id"), ["batch_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rejected_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rejected_record_batch_id"))

    op.drop_table("rejected_record")
    with op.batch_alter_table("ingested_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingested_record_external_id"))
        batch_op.drop_index(batch_op.f("ix_ingested_record_batch_id"))

    op.drop_table("ingested_record")
    with op.batch_alter_table("chat_transcript_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_transcript_item_session_id"))
        batch_op.drop_index(batch_op.f("ix_chat_transcript_item_seq"))

    op.drop_table("chat_transcript_item")
    op.drop_table("chat_memory_entry")
    with op.batch_alter_table("ingestion_batch", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ingestion_batch_source"))

    op.drop_table("ingestion_batch")
    with op.batch_alter_table("chat_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_session_user_id"))

    op.drop_table("chat_session")
    with op.batch_alter_table("api_key", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_key_principal_id"))

    op.drop_table("api_key")
    # ### end Alembic commands ###
