"""graph extraction watermark

The second reader of the transcript gets its own watermark, which is what
``chat_memory_extraction`` predicted when it declined to be a column on
``chat_session``: "a second reader of the transcript would want its own
watermark, and a column named for one of them would be the wrong shape
immediately."

A new table, so nothing here can fail the way an ALTER on a populated one does:
no backfill, and no NOT NULL column to fail against existing rows.

**No seeding, and that is the decision.** Every existing session gets no row,
resolving to ``-1``, so the first graph-extraction run on an old conversation
reads it from the beginning — bounded by the extractor's own per-run message cap,
so a long history drains across turns rather than arriving as one enormous model
call. Seeding at each session's current maximum ``seq`` was the alternative and
would declare every conversation already extracted, discarding the entire corpus
this feature exists to read. That is the same call ``chat_memory_extraction``
made, for the same reason.

Autogenerated against a running Postgres and read against ``graph/models.py``
before being kept; the drift test is what proves the two agree.

Revision ID: 6885a8d19fd8
Revises: b277807cdec5
Create Date: 2026-08-23 23:10:00.205321
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "6885a8d19fd8"
down_revision: Union[str, None] = "b277807cdec5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_extraction",
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("through_seq", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_session.session_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("graph_extraction")
    # ### end Alembic commands ###
