"""memory graph assertion log

The schema for ADR 0006 — the part of the memory graph that is expensive to
change once there are rows, landing before anything writes to it.

Four new tables and no ALTER, so none of the traps the earlier migrations hit
apply: nothing to backfill, and no ``ADD COLUMN ... NOT NULL`` to fail against
existing rows. That is deliberate rather than lucky. ADR 0002 sketched an edge
table keyed by ``(user_id, src, rel, dst)``, and had it been built, this would
have been a primary key change on a populated table instead of a create.

Autogenerated against a running Postgres and then read line by line, which the
repository's ``CLAUDE.md`` asks for and which the previous migration could not
do. Two things were checked rather than assumed:

- ``sa.DateTime(timezone=True)`` on all four temporal columns, because a naive
  timestamp compares as local time and the difference is invisible until it is
  a bug. This is the same reason SQLite was removed from the test suite.
- The valid-time columns are nullable and the recorded-time end is nullable,
  because ``NULL`` carries meaning here: *unknown* for a valid bound, *still
  believed* for ``recorded_until``. An open-ended fact is ``datetime.max``, not
  ``NULL`` and not ``'infinity'`` — psycopg 3 raises ``DataError`` reading
  ``'infinity'::timestamptz`` back, so a row carrying it would be perfectly
  valid in SQL and fatal to every Python caller. See ``graph/models.py``.

There is no backfill and there is nothing to seed. Every existing session's
transcript remains the source these tables will eventually be derived from, and
extraction reads forward from its own watermark, so an empty graph is the
correct starting state rather than a gap.

No pgvector, no embedding column, no ``graph_node_vec``. Those belong to the
retrieval phase, which ADR 0006 puts last on purpose, and enabling the extension
is a change to what this project requires of Postgres — worth its own migration
and its own review rather than riding along with a schema nobody queries yet.

Revision ID: b277807cdec5
Revises: 0057489a3ed5
Create Date: 2026-08-23 19:32:20.884794
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "b277807cdec5"
down_revision: Union[str, None] = "0057489a3ed5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_assertion",
        sa.Column("assertion_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("src", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dst", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attrs", sa.JSON(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trust", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("assertion_id"),
        sa.UniqueConstraint(
            "user_id", "src", "rel", "dst", "recorded_at", name="uq_assertion_claim_recorded"
        ),
    )
    op.create_index(op.f("ix_graph_assertion_run_id"), "graph_assertion", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_graph_assertion_session_id"), "graph_assertion", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_graph_assertion_user_id"), "graph_assertion", ["user_id"], unique=False
    )
    op.create_table(
        "graph_conclusion",
        sa.Column("conclusion_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("statement", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("derived_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("conclusion_id"),
    )
    op.create_index(
        op.f("ix_graph_conclusion_status"), "graph_conclusion", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_graph_conclusion_user_id"), "graph_conclusion", ["user_id"], unique=False
    )
    op.create_table(
        "graph_node",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("node_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attrs", sa.JSON(), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "node_id"),
    )
    op.create_table(
        "graph_conclusion_evidence",
        sa.Column("conclusion_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("assertion_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assertion_id"],
            ["graph_assertion.assertion_id"],
        ),
        sa.ForeignKeyConstraint(
            ["conclusion_id"],
            ["graph_conclusion.conclusion_id"],
        ),
        sa.PrimaryKeyConstraint("conclusion_id", "assertion_id"),
    )
    op.create_index(
        op.f("ix_graph_conclusion_evidence_assertion_id"),
        "graph_conclusion_evidence",
        ["assertion_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_graph_conclusion_evidence_assertion_id"), table_name="graph_conclusion_evidence"
    )
    op.drop_table("graph_conclusion_evidence")
    op.drop_table("graph_node")
    op.drop_index(op.f("ix_graph_conclusion_user_id"), table_name="graph_conclusion")
    op.drop_index(op.f("ix_graph_conclusion_status"), table_name="graph_conclusion")
    op.drop_table("graph_conclusion")
    op.drop_index(op.f("ix_graph_assertion_user_id"), table_name="graph_assertion")
    op.drop_index(op.f("ix_graph_assertion_session_id"), table_name="graph_assertion")
    op.drop_index(op.f("ix_graph_assertion_run_id"), table_name="graph_assertion")
    op.drop_table("graph_assertion")
    # ### end Alembic commands ###
