"""memory extraction watermark

Adds the bookkeeping table for the transcript extractor, for the application's
ADR 0002. It holds no memory — only how far each session has been read.

A new table, so none of the traps the earlier migrations hit apply: no existing
rows for a NOT NULL column to fail against, and nothing to backfill.

The absence of a backfill is the decision again, and it points the opposite way
from ADR 0021's. Every existing session gets no row, which resolves to a
watermark of ``-1`` and means the first extraction run on an old conversation
reads it from the beginning — bounded by ``MAX_MESSAGES_PER_RUN``, so a long
history drains across turns rather than arriving as one enormous model call.
Seeding existing sessions at their current maximum ``seq`` was the alternative
and would have declared every conversation already extracted, silently
discarding the entire corpus this feature exists to read.

``through_seq`` defaults to ``-1`` rather than ``0`` because position ``0`` is a
real transcript item: a default of ``0`` would skip the first message of every
session, which is the one most likely to carry a standing preference.

Written by hand rather than autogenerated, because Postgres was not running.
Read it against ``chat/models.py`` before trusting it; the drift test is what
proves the two agree.

Revision ID: b7c2a91f4d05
Revises: e90754c14d4c
Create Date: 2026-08-14
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "b7c2a91f4d05"
down_revision: Union[str, None] = "e90754c14d4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "chat_memory_extraction",
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("through_seq", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_session.session_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )


def downgrade() -> None:
    op.drop_table("chat_memory_extraction")
