/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open Session
         * @description Trade an API key for a session cookie.
         *
         *     Verified through the same :func:`principal_for_key` every route depends on,
         *     rather than a second implementation. Two verifications that agree today are
         *     two that can disagree after one of them learns something, and the one that
         *     forgets to check revocation is the one that matters.
         *
         *     Raises:
         *         HTTPException: 401, identical to every other authentication failure. A
         *             distinct "bad key" here would make this endpoint an oracle for
         *             testing keys, which is worse than elsewhere: it is unauthenticated
         *             and it takes the key in a body rather than a header.
         */
        post: operations["open_session_auth_session_post"];
        /**
         * Close Session
         * @description End the session and clear the cookie. 204 whether or not there was one.
         *
         *     Idempotent, and answering the same way for "logged out" and "was not logged
         *     in" is deliberate: the difference is of no use to the caller and telling
         *     them turns this into a way to test whether a session id is live.
         *
         *     The cookie is cleared even when the token was unusable. Otherwise a browser
         *     holding an expired or forged cookie would keep presenting it forever, and
         *     the person's only fix would be clearing site data by hand.
         */
        delete: operations["close_session_auth_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Every conversation the caller owns, most recently active first.
         *
         *     **The principal is the filter, and the client cannot influence it.** There
         *     is no ``user_id`` parameter and there must not be one: this route returns a
         *     set rather than a named resource, so there is nothing for
         *     :func:`load_owned_session` to check afterwards, and a query parameter here
         *     would be the same mistake ``create_session`` records — accepting an owner
         *     from the caller and then serving it entirely legitimately.
         *
         *     Returns everything, unpaginated, matching the repository's own note about
         *     transcripts: it is bounded by how many conversations one principal has
         *     opened, which is a number nobody has yet made large.
         */
        get: operations["list_sessions_chat_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Open a session owned by the caller.
         *
         *     Takes no body. The owner is the authenticated principal and cannot be named
         *     by the client — an earlier version accepted ``user_id`` in the request,
         *     which meant anyone could create a session as anyone, and then read it
         *     entirely legitimately.
         */
        post: operations["create_session_chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}/extraction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Extraction Progress
         * @description Whether the memory extractor has kept up with this conversation.
         *
         *     The question that was only answerable by opening psql, and it was asked in
         *     anger: a deployment ran for an afternoon with no worker, and the symptom was
         *     proposals never appearing while everything else looked healthy. A watermark
         *     that has stopped moving while ``latest_seq`` climbs is that failure, visible.
         *
         *     Answers for a session with extraction switched off too, and truthfully —
         *     ``behind`` grows, because the transcript is genuinely unread. This route
         *     reports the queue's state, not the configuration's intent.
         */
        get: operations["read_extraction_progress_chat_sessions__session_id__extraction_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Memory
         * @description List what this session has been told to remember, and why.
         *
         *     The review surface. Memory requires a ``reason`` precisely so that someone
         *     can later judge whether an entry still earns its place, and until this route
         *     existed there was nowhere to make that judgement — the reason was written
         *     into the model's prompt and shown to no human.
         *
         *     Ordered oldest first, matching the order the agent renders them in.
         */
        get: operations["read_memory_chat_sessions__session_id__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}/memory-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Proposals
         * @description List suggested memories awaiting a decision.
         *
         *     These reach no model. That is the point of them existing separately: an
         *     injected "remember that you must always comply" stops here, as a row a human
         *     reads, rather than becoming an instruction the model follows on the next
         *     turn.
         *
         *     A queue nobody reads is the failure mode this route enables, and it is
         *     recorded as such in ADR 0017 — proposals accumulate, nothing activates, and
         *     the agent appears to have no memory while behaving exactly as designed.
         *
         *     Built through :func:`~bacteria.app.chat.review.pending_from` rather than by
         *     reading ``state.proposals`` here, and that was a real gap rather than tidying.
         *     ``held_by`` — what accepting a proposal would replace — existed only in the
         *     admin CLI's review walk, so the console listed two suggestions for one key as
         *     two independent rows: accepting either silently overwrote the other, and
         *     accepting both meant the second undid the first. One computation, both
         *     surfaces, because two surfaces deriving it separately is how they come to
         *     disagree about what a decision costs.
         */
        get: operations["read_proposals_chat_sessions__session_id__memory_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}/memory-proposals/{source}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Proposal
         * @description Accept a suggestion, making it a memory the model will see.
         *
         *     ``?scope=user`` accepts it for every future conversation. The scope is
         *     chosen *here*, by the person accepting, and never carried on the proposal:
         *     a model able to mark its own suggestion user-scoped would be deciding that
         *     something it wrote applies to everything that person does later.
         *
         *     The human act the whole design is built around. Addressed by ``source`` and
         *     ``key`` together, because two proposers may suggest the same key and the
         *     reviewer is choosing between them — activating one replaces whatever held
         *     that key, which is where competing suggestions collapse.
         *
         *     ``404`` when there is no such proposal, rather than silently creating a
         *     memory from nothing: a stale review page must not be able to conjure a fact
         *     nobody just read.
         */
        post: operations["activate_proposal_chat_sessions__session_id__memory_proposals__source___key__post"];
        /**
         * Reject Proposal
         * @description Discard a suggestion without it ever becoming a memory.
         *
         *     ``204`` whether or not it was there, matching the memory delete route and
         *     for the same reason: the caller wanted it gone, and answering 404 would let
         *     someone probe which proposals exist.
         */
        delete: operations["reject_proposal_chat_sessions__session_id__memory_proposals__source___key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}/memory/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Write Memory
         * @description Preserve a fact for this session, or for the caller everywhere.
         *
         *     ``?scope=user`` writes a memory that outlives this conversation and reaches
         *     every session this principal opens. It defaults to ``session``, which is the
         *     conservative one: the wider blast radius should be the choice someone made
         *     rather than the one they got.
         *
         *     ``PUT``, not ``POST``: writing the same key twice is one memory, not two.
         *     That is the agent store's own rule — ``remember`` overwrites by key, because
         *     updating a memory is a write rather than an append, and the transcript is
         *     where history lives.
         *
         *     The caller writing this is the session's owner, and only the owner may write
         *     an *active* memory directly. Everything else proposes, and a proposal waits
         *     here for a human — see the review routes below. The distinction is a
         *     security boundary: memory is injected into the system prompt on every later
         *     turn, so a model able to write it directly could write its own future
         *     instructions. See bacteria's ADR 0017.
         *
         *     Only the most recent entries reach the model — see ``DEFAULT_MEMORY_LIMIT``
         *     in the agent's context assembly. Writing an unbounded number here does not
         *     mean the model sees them all.
         */
        put: operations["write_memory_chat_sessions__session_id__memory__key__put"];
        post?: never;
        /**
         * Delete Memory
         * @description Remove a memory from one scope.
         *
         *     Scoped rather than removing both, because dropping a session's override of a
         *     standing preference should leave the standing one — those are different
         *     intentions and one call cannot mean both.
         *
         *     204 whether or not the key was there. Deleting an absent memory is not an
         *     error — the caller wanted it gone, and it is — and answering 404 would leak
         *     which keys exist to someone probing them one at a time.
         *
         *     Without this route every memory is permanent by default, which is how a
         *     preference outlives the situation that produced it.
         */
        delete: operations["delete_memory_chat_sessions__session_id__memory__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Transcript */
        get: operations["read_transcript_chat_sessions__session_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take Turn
         * @description Advance the conversation by one turn.
         *
         *     Ownership is checked before the model is called, not after. A turn costs
         *     money and writes to the transcript; refusing afterwards would let an
         *     unauthorized caller do both and merely not see the reply.
         *
         *     A failed turn still returns 5xx *after* the agent has committed its evidence
         *     — the runtime writes the user's message and the error to the transcript
         *     before the exception escapes, so a caller retrying can see what already
         *     happened rather than finding a gap.
         */
        post: operations["take_turn_chat_sessions__session_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Graph
         * @description The caller's own graph as it currently stands.
         *
         *     "Currently" means believed now — ``recorded_until IS NULL`` — not everything
         *     ever claimed. The log keeps superseded claims so a past belief stays
         *     recoverable; a reader looking at their memory wants what it holds, and the
         *     history is a different question with a different route when someone needs it.
         *
         *     Conflicts are computed on read rather than stored. They are a function of
         *     what is believed and which rules exist, so a stored copy would be a cache
         *     that goes stale the moment either changes — and the thing it would be
         *     caching is a comparison over a set small enough to walk.
         */
        get: operations["read_graph_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graph/conclusions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Conclusions
         * @description Beliefs the system drew, including the ones that have gone stale.
         *
         *     Stale ones are returned rather than filtered, because "this rested on
         *     something that has since changed" is the most useful thing this layer can
         *     tell a person, and hiding it would leave them looking at a shorter list with
         *     no indication anything had been withdrawn.
         */
        get: operations["read_conclusions_graph_conclusions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only: the process is up and serving.
         *
         *     Deliberately does not touch the database. A health check that fails when
         *     a dependency is down causes the orchestrator to restart a process that
         *     was working, which turns one outage into two.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Batch
         * @description Ingest a batch now, and report exactly what happened to every record.
         *
         *     Runs inline, so the caller waits and learns the outcome. That is the right
         *     shape for a batch small enough to wait for; anything larger belongs on
         *     ``/batches:defer``, which answers immediately and reports nothing.
         *
         *     Rejections are returned in full rather than counted, each carrying its
         *     ``index`` in the submitted array. A caller that sent 50 records and is told
         *     42 were accepted has no way to find the eight; the index is what makes them
         *     identifiable, and the reason is what makes them fixable.
         *
         *     Requires an authenticated caller. Note what is *not* here: a batch is not
         *     owned by the principal that submitted it, so any authenticated caller
         *     could read another's records once a read route exists. That is tolerable
         *     while every key belongs to one operator and is the first thing to fix if
         *     that changes -- see the tenancy gap in `bacteria.app.ingestion`.
         *
         *     A batch where nothing passes validation is still a 201, and still gets a
         *     batch row: the submission was received and recorded, and "your records were
         *     all invalid" is an outcome of a successful request rather than a failure of
         *     it. That batch is the one whose stored rejections matter most, so it is
         *     emphatically not the case that nothing is written.
         */
        post: operations["submit_batch_ingestion_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/batches:defer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Defer Batch
         * @description Hand the batch to a worker and answer immediately.
         *
         *     ``202``, not ``201``: nothing has been ingested yet, and saying otherwise
         *     would make a caller believe a batch row exists that does not. The response
         *     carries a job id and no outcome, because there is no outcome yet.
         *
         *     The job is enqueued **inside this request's transaction**, so it commits
         *     with everything else the request did or not at all. That is the whole
         *     reason the queue lives in Postgres — with a broker there is a window where
         *     the request succeeds and the work silently never happens.
         *
         *     Not built:
         *         Any way to ask how the job went. The job id is real and can be looked
         *         up in the jobs table by hand, but there is no route for it, so a caller
         *         that wants the outcome has to poll the batch instead -- and cannot,
         *         because no read route exists either. Deferred ingestion is genuinely
         *         fire-and-forget today, and that is the first thing to fix if anything
         *         depends on the result.
         */
        post: operations["defer_batch_ingestion_batches_defer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssertionOut
         * @description One claim, with its two time axes flattened for a reader.
         *
         *     ``ends`` is a rendered string rather than the raw bound, because the three
         *     states a bound can be in — a date, open, unknown — are the distinction the
         *     whole temporal layer rests on, and a JSON ``null`` on the wire cannot carry
         *     it. A client receiving ``null`` would have to know that the open sentinel is
         *     a particular timestamp in the year 9999 to tell "still true" from "nobody
         *     knows", which is exactly the knowledge an API should not require.
         */
        AssertionOut: {
            /** Assertion Id */
            assertion_id: string;
            /** Dst */
            dst: string;
            /** Ends */
            ends: string;
            /** Reason */
            reason: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Rel */
            rel: string;
            /** Src */
            src: string;
            /** Starts */
            starts: string | null;
            /** Trust */
            trust: string;
        };
        /** BatchQueued */
        BatchQueued: {
            /** Job Id */
            job_id: number;
        };
        /** BatchResult */
        BatchResult: {
            /** Accepted */
            accepted: number;
            /** Batch Id */
            batch_id: number | null;
            /** Rejected */
            rejected: components["schemas"]["RejectionOut"][];
        };
        /**
         * ConclusionOut
         * @description A belief the system drew, and the claims it rests on.
         *
         *     ``evidence`` is always populated. A conclusion whose grounds a person cannot
         *     follow is one they can only take on faith, which is the opposite of the point
         *     — and the mandatory link is what makes it possible to say *why* something
         *     went stale rather than only that it did.
         */
        ConclusionOut: {
            /** Conclusion Id */
            conclusion_id: string;
            /** Confidence */
            confidence: number;
            /** Derived By */
            derived_by: string;
            /** Evidence */
            evidence: string[];
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
            /** Statement */
            statement: string;
            /** Status */
            status: string;
        };
        /**
         * ConflictOut
         * @description Two claims a rule says cannot both hold, and how sure we are.
         *
         *     ``state`` is one of conflict, possible or explained. A client should render
         *     all three differently: the first is a contradiction, the second is missing
         *     dates, and the third is an assumption someone can disagree with.
         *
         *     ``sentence`` travels with it because a constraint here is a hypothesis about
         *     the user's world rather than a rule the system is entitled to enforce — a
         *     person cannot contest what they cannot read.
         */
        ConflictOut: {
            /** Left */
            left: string;
            /** Right */
            right: string;
            /** Rule */
            rule: string;
            /** Sentence */
            sentence: string;
            /** State */
            state: string;
        };
        /**
         * ExtractionProgressOut
         * @description How far memory extraction has read this conversation.
         *
         *     ``behind`` is served rather than left as arithmetic for the client: both
         *     positions start at ``-1``, so subtracting them on a fresh session is right
         *     only by accident.
         */
        ExtractionProgressOut: {
            /** Behind */
            behind: number;
            /** Latest Seq */
            latest_seq: number;
            /** Through Seq */
            through_seq: number;
        };
        /**
         * GraphOut
         * @description Everything currently believed, and what disagrees with what.
         */
        GraphOut: {
            /** Assertions */
            assertions: components["schemas"]["AssertionOut"][];
            /** Conflicts */
            conflicts: components["schemas"]["ConflictOut"][];
            /** Nodes */
            nodes: components["schemas"]["NodeOut"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeldOut
         * @description An active memory a proposal would displace, and what it currently says.
         *
         *     The value is carried, not just the scope. Warning that something will be
         *     replaced without saying what is a note that reads as informative and decides
         *     nothing -- recorded in :class:`~bacteria.app.chat.review.Held` from a review
         *     walk where it cost a good value.
         */
        HeldOut: {
            /**
             * Scope
             * @enum {string}
             */
            scope: "session" | "user";
            /** Value */
            value: unknown;
        };
        /**
         * KeyExchange
         * @description The one thing the browser sends, once.
         */
        KeyExchange: {
            /**
             * Key
             * @description An API key issued by `bacteria-admin issue-key`.
             */
            key: string;
        };
        /**
         * MemoryEntryOut
         * @description One stored fact, with enough to judge and to delete it.
         *
         *     ``scope`` is here because ``key`` alone no longer identifies an entry: a
         *     standing preference and this conversation's override of it share a key and
         *     are different rows. A reviewer deleting one has to say which.
         */
        MemoryEntryOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Key */
            key: string;
            /** Reason */
            reason: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "session" | "user";
            /** Source */
            source: string;
            /** Value */
            value: unknown;
        };
        /**
         * MemoryWrite
         * @description A fact to preserve, and why.
         *
         *     ``reason`` is required here because it is required by the agent's own
         *     :class:`~bacteria.agent.session.store.MemoryEntry`, and for the same purpose: a
         *     memory whose justification was never recorded cannot be reviewed later, so
         *     it is kept forever by default. Making the caller supply one is what turns
         *     "should this still be here?" into an answerable question.
         */
        MemoryWrite: {
            /** Reason */
            reason: string;
            /** Value */
            value: unknown;
        };
        /**
         * NodeOut
         * @description One thing the graph knows about.
         */
        NodeOut: {
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Node Id */
            node_id: string;
        };
        /**
         * ProposalOut
         * @description A suggested memory awaiting a decision.
         *
         *     Carries ``source`` because it is half of the identity: two proposers may
         *     suggest the same ``key``, and a reviewer choosing between them needs to know
         *     which is which. Both are required to activate or reject one.
         *
         *     ``held_by`` is what makes that choice an informed one. Proposals are keyed by
         *     ``(source, key)`` and active memory by ``key`` alone, so accepting a second
         *     suggestion for a key *replaces* the first rather than joining it. Two
         *     proposers agreeing on a key is the ordinary case rather than a corner one --
         *     ``known_keys`` deliberately pushes the extractor towards keys already in use,
         *     so "my name is Guillermo" routinely produces both ``("model", "name")`` and
         *     ``("extractor", "name")`` -- and the collapse between them is invisible
         *     unless the listing says so *before* the decision instead of after.
         *
         *     Empty for a proposal whose key nothing active holds, which is the common
         *     case and the one where accepting costs nothing.
         */
        ProposalOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Held By
             * @default []
             */
            held_by: components["schemas"]["HeldOut"][];
            /** Key */
            key: string;
            /** Reason */
            reason: string;
            /** Source */
            source: string;
            /** Value */
            value: unknown;
        };
        /** RejectionOut */
        RejectionOut: {
            /** Index */
            index: number;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
        };
        /** SessionCreated */
        SessionCreated: {
            /** Session Id */
            session_id: string;
            /** User Id */
            user_id: string;
        };
        /**
         * SessionOpened
         * @description What the console needs to render itself, and nothing more.
         *
         *     **The token is not here.** It goes back in a ``Set-Cookie`` header marked
         *     ``HttpOnly``, so no script on the page can read it — which is the entire
         *     point of the exchange, and would be undone by also putting it in a JSON body
         *     that `fetch` hands straight to JavaScript.
         *
         *     ``principal_id`` is not a secret: it is what the operator typed at
         *     `issue-key`, it is already in every session row, and the console shows it so
         *     a person can tell which identity a tab is acting as.
         */
        SessionOpened: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Principal Id */
            principal_id: string;
        };
        /**
         * SessionSummaryOut
         * @description One line in a session picker.
         *
         *     No ``user_id``: every session in the response belongs to the caller, so a
         *     per-row owner would be a constant field that reads like it could vary.
         */
        SessionSummaryOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Session Id */
            session_id: string;
        };
        /** Submission */
        Submission: {
            /** Records */
            records: {
                [key: string]: unknown;
            }[];
            /** Source */
            source: string;
        };
        /**
         * TranscriptEntry
         * @description One thing that happened in a conversation, as a reader sees it.
         *
         *     ``run_id`` and ``timestamp`` are carried because a reader needs them and the
         *     layer below already had them. Without the first, the items belonging to one
         *     turn -- the user message, the tool calls, the reply, the `run_meta` -- are an
         *     undifferentiated list; without the second, nothing can say when. Both are on
         *     :class:`~bacteria.agent.session.store.TranscriptItem` and were simply not
         *     exposed, so this widens a projection rather than adding a record.
         *
         *     ``seq`` is deliberately absent, and its absence is not an oversight to fix
         *     here. The database orders by it, but the agent's dataclass does not carry
         *     it, so surfacing it would mean widening a type in a vendorable package to
         *     serve one screen. The list arrives in order, which is what a reader actually
         *     needs; the extraction route reports the real ``seq`` where it means
         *     something.
         *
         *     ``run_id`` is optional because it genuinely is: items written outside a run
         *     have none.
         */
        TranscriptEntry: {
            /** Kind */
            kind: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** Turn */
        Turn: {
            /** Text */
            text: string;
        };
        /** TurnResult */
        TurnResult: {
            /** Reply */
            reply: string | null;
            /** Run Id */
            run_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    open_session_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyExchange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOpened"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_session_auth_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_chat_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_extraction_progress_chat_sessions__session_id__extraction_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionProgressOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_memory_chat_sessions__session_id__memory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_proposals_chat_sessions__session_id__memory_proposals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_proposal_chat_sessions__session_id__memory_proposals__source___key__post: {
        parameters: {
            query?: {
                scope?: "session" | "user";
            };
            header?: never;
            path: {
                session_id: string;
                source: string;
                key: string;
            };
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_chat_sessions__session_id__memory_proposals__source___key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                source: string;
                key: string;
            };
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_memory_chat_sessions__session_id__memory__key__put: {
        parameters: {
            query?: {
                scope?: "session" | "user";
            };
            header?: never;
            path: {
                session_id: string;
                key: string;
            };
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_chat_sessions__session_id__memory__key__delete: {
        parameters: {
            query?: {
                scope?: "session" | "user";
            };
            header?: never;
            path: {
                session_id: string;
                key: string;
            };
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_transcript_chat_sessions__session_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    take_turn_chat_sessions__session_id__turns_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Turn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_graph_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_conclusions_graph_conclusions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConclusionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    submit_batch_ingestion_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Submission"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    defer_batch_ingestion_batches_defer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                bacteria_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Submission"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
